# Generated by Django 3.0.5 on 2020-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('emai_address', models.CharField(max_length=30)),
                ('home_address', models.CharField(max_length=30)),
                ('account_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('emai_address', models.CharField(max_length=30)),
                ('home_address', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('owner_emai_address', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
            ],
        ),
    ]
