# Generated by Django 3.0.5 on 2020-10-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emai_address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='dperson',
            old_name='emai_address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='owner_emai_address',
            new_name='owner_email_address',
        ),
    ]
