# Generated by Django 3.0.5 on 2020-10-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_auto_20201029_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dperson',
            name='confirm_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dperson',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dperson',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='confirm_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
