# Generated by Django 3.0.5 on 2020-10-31 02:15

from django.db import migrations, models
import mobileapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_auto_20201030_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='dperson',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=mobileapp.models.upload_path),
        ),
    ]
