# Generated by Django 3.0.5 on 2020-10-31 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0004_dperson_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dperson',
            old_name='cover',
            new_name='licens',
        ),
    ]
