# Generated by Django 3.0.5 on 2020-10-31 02:26

from django.db import migrations, models
import mobileapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0005_auto_20201031_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='dperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=mobileapp.models.upload_path),
        ),
    ]
